version: "3.9"

services:

  adf-self-hosted-runtime:
    image: $IMAGE_REGISTRY/$IMAGE_REPOSITORY:$IMAGE_VERSION
    environment:
        ENABLE_HA: "true"
        AUTH_KEY: $PRODUCTION_CONNECTION_STRING
    restart: always
    isolation: process
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: single
  
  logging:
    image: fluent/fluentd:v1.14-windows-20H2-1
    command: ["-c", "c:\\fluent\\conf\\fluentd.conf"]
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd:C:\fluent\conf
      - ./logs:C:\fluent\log